- name: MapsBroker Settig
  win_command: powershell.exe -
  args:
    stdin: "Set-Service MapsBroker -StartupType Disabled"

# - name: iphlpsvc Setting
#   win_command: powershell.exe -
#   args:
#     stdin: "Set-Service iphlpsvc -StartType Disabled"