- name: Set timezone to 'GMT Standard Time' (GMT)
  win_timezone:
    timezone: Tokyo Standard Time
# https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11)?redirectedfrom=MSDN